name = "opencvcore_ada"
description = "Thick Ada binding to OpenCV Core Library"
version = "0.1.0-dev"

authors = ["Zack Boll"]
maintainers = ["Zack Boll <zackboll@gmail.com>"]
maintainers-logins = ["zackboll"]
licenses = "Apache-2.0"
website = ""
tags = ["opencv", "computer-vision", "binding", "ada"]
