#!/bin/sh

set -eu

output=config/opencv_core_install.gpr
sysname=$(uname -s)

# Prefer the MinGW target-prefixed pkg-config on MSYS2/MinGW Windows.
# The generic "pkg-config" name can resolve to Strawberry Perl's
# pkg-config.bat, which does not see MSYS2 OpenCV metadata.
pkg_config=pkg-config
case "$sysname" in
    MINGW*|MSYS*)
        if command -v x86_64-w64-mingw32-pkg-config >/dev/null 2>&1; then
            pkg_config=x86_64-w64-mingw32-pkg-config
        fi
        ;;
esac

if ! command -v "$pkg_config" >/dev/null 2>&1; then
    echo "error: $pkg_config is required to locate OpenCV Core" >&2
    exit 1
fi

package=
for candidate in opencv5 opencv4 opencv
do
    if "$pkg_config" --exists "$candidate"; then
        package=$candidate
        break
    fi
done

# MacPorts installs opencv4 pkg-config metadata under
# <prefix>/lib/opencv4/pkgconfig rather than the normal
# <prefix>/lib/pkgconfig directory. Only search that location when the
# usual lookup failed; pkg-config remains authoritative afterwards.
if [ -z "$package" ]; then
    if [ "$sysname" = "Darwin" ] && command -v port >/dev/null 2>&1; then
        macports_prefix=$(dirname "$(dirname "$(command -v port)")")
        macports_pkgconfig="${macports_prefix}/lib/opencv4/pkgconfig"
        if [ -d "$macports_pkgconfig" ]; then
            PKG_CONFIG_PATH="${macports_pkgconfig}${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}"
            export PKG_CONFIG_PATH
            for candidate in opencv5 opencv4 opencv
            do
                if "$pkg_config" --exists "$candidate"; then
                    package=$candidate
                    break
                fi
            done
        fi
    fi
fi

if [ -z "$package" ]; then
    echo "error: pkg-config package was not found (tried opencv5, opencv4, opencv)" >&2
    exit 1
fi

include_dir=$("$pkg_config" --variable=includedir "$package")

if [ -z "$include_dir" ]; then
    include_dir=$("$pkg_config" --variable=includedir_new "$package")
fi

library_dir=$("$pkg_config" --variable=libdir "$package")

if [ -z "$include_dir" ] || [ -z "$library_dir" ]; then
    echo "error: '$package' does not define a usable include directory and libdir" >&2
    exit 1
fi

# macOS OpenCV from Homebrew or MacPorts is built with Apple clang++ and
# libc++. The C++ shim must use that same compiler and runtime. Linux
# OpenCV uses g++ and libstdc++, which remains the default.
cxx_runtime_switch="-lstdc++"
cxx_driver="g++"
use_apple_clang="False"
macos_sdk_root=""

if [ "$sysname" = "Darwin" ]; then
    use_apple_clang="True"
    cxx_runtime_switch="-lc++"
    if ! command -v xcrun >/dev/null 2>&1; then
        echo "error: xcrun is required to locate Apple clang++ and the macOS SDK" >&2
        exit 1
    fi
    cxx_driver=$(xcrun --find clang++)
    if [ -z "$cxx_driver" ]; then
        echo "error: Apple clang++ is required to compile the OpenCV C++ shim on macOS" >&2
        exit 1
    fi
    macos_sdk_root=$(xcrun --sdk macosx --show-sdk-path)
    if [ -z "$macos_sdk_root" ]; then
        echo "error: could not resolve the macOS SDK path via xcrun --sdk macosx --show-sdk-path" >&2
        exit 1
    fi
fi

# Linux and macOS keep -L<libdir> -lopencv_core. Windows links the OpenCV
# Core import library by absolute path into the shim DLL so the Ada
# executable does not search the whole MSYS2 mingw64/lib directory.
opencv_core_link_option="-lopencv_core"
use_direct_opencv_link="False"
use_windows_shared_shim="False"

case "$sysname" in
    MINGW*|MSYS*)
        opencv_core_import_library="${library_dir}/libopencv_core.dll.a"
        if [ ! -f "$opencv_core_import_library" ]; then
            echo "error: OpenCV Core import library was not found: $opencv_core_import_library" >&2
            exit 1
        fi
        opencv_core_link_option="$opencv_core_import_library"
        use_direct_opencv_link="True"
        use_windows_shared_shim="True"
        ;;
esac

case "$include_dir$library_dir$cxx_driver$macos_sdk_root$opencv_core_link_option" in
    *\"*)
        echo "error: OpenCV paths containing double quotes are unsupported" >&2
        exit 1
        ;;
esac

mkdir -p config

cat >"$output" <<EOF
--  Generated by scripts/configure_opencv.sh; do not edit.
abstract project OpenCV_Core_Install is
   type Apple_Clang_Kind is ("True", "False");
   type Direct_OpenCV_Link_Kind is ("True", "False");
   type Windows_Shared_Shim_Kind is ("True", "False");
   Use_Apple_Clang : Apple_Clang_Kind := "${use_apple_clang}";
   Use_Direct_OpenCV_Link : Direct_OpenCV_Link_Kind := "${use_direct_opencv_link}";
   Use_Windows_Shared_Shim : Windows_Shared_Shim_Kind := "${use_windows_shared_shim}";
   Include_Switch := "-I${include_dir}";
   Library_Search_Switch := "-L${library_dir}";
   OpenCV_Core_Link_Option := "${opencv_core_link_option}";
   Cxx_Runtime_Switch := "${cxx_runtime_switch}";
   Cxx_Driver := "${cxx_driver}";
   MacOS_SDK_Root := "${macos_sdk_root}";
end OpenCV_Core_Install;
EOF
