#!/bin/sh

set -eu

package=opencv4
output=config/opencvcore_ada_opencv.gpr

if ! command -v pkg-config >/dev/null 2>&1; then
    echo "error: pkg-config is required to locate OpenCV Core" >&2
    exit 1
fi

if ! pkg-config --exists "$package"; then
    echo "error: pkg-config package '$package' was not found" >&2
    exit 1
fi

include_dir=$(pkg-config --variable=includedir "$package")
library_dir=$(pkg-config --variable=libdir "$package")

if [ -z "$include_dir" ] || [ -z "$library_dir" ]; then
    echo "error: '$package' does not define includedir and libdir" >&2
    exit 1
fi

case "$include_dir$library_dir" in
    *\"*)
        echo "error: OpenCV paths containing double quotes are unsupported" >&2
        exit 1
        ;;
esac

mkdir -p config

cat >"$output" <<EOF
--  Generated by scripts/configure_opencv.sh; do not edit.
abstract project Opencvcore_Ada_OpenCV is
   Include_Switch := "-I${include_dir}";
   Library_Search_Switch := "-L${library_dir}";
end Opencvcore_Ada_OpenCV;
EOF